# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_app', '0003_auto_20170105_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_pass',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
